### ISSUE TITLE
Can't start the responsive mode for bracket.

### ISSUE THREAD

**Issue by Athax** [brimelow/Response-for-Brackets#59]
Idk what is wrong, when i try to press the button the little ipod thingy it does not start the responsive mode.

**Comment by ikbenben** [comment]
@Athax , this should work now with with release 0.0.6. You are now able to set the Preview URL in File > Project Settings. After that you can use the Response Menu to use that URL instead of the local file. When you switch to Responsive mode, the preview pane will load the url you have specified
