### ISSUE TITLE
Queries being over written/disappearing and temp file

### ISSUE THREAD

**Issue by awakekat** [brimelow/Response-for-Brackets#61]
Learning how to use this tool as I go. A 'temp-response.css' file shows up with current query and classes I am changing. Sometimes the files are "transferred" to the 'media-queries.css' file and sometimes not, being over written, stripping out previous classes in queries - not cool! The designated query point stays, but the inner classes go *poof*. I have seen multiple classes in varying letter lengths as if the file is saving after typing each letter, then creating the same class again with another letter added. Very odd.
I will make a collection of screencasts and images. All current versions of Chrome, Yosemite and Brackets.

**Comment by ikbenben** [comment]
@awakekat I'm going to close this as I haven't heard back from you. I believe the issues that were opened cover what you have highlighted here

**Comment by randyb59** [comment]
I am running 
- Brackets (Release 1.6 build 1.6.0-16680 (release 3df0ac6fa)) 
- on Mac OS 10.11 El Capitan. 
- with "Response for Brackets - original" v-1.0. 

I'll preface this by saying I'm a new web developer, currently finishing up a 2 year IT Software Development program at my local tech college. I installed the plugin yesterday and began using it. I'm having a host of issues. 
1. Like Katherine, changes I make often simply disappear from the media-queries.css file and I have no clue why. 
2. When I get things "responding" they way they should in the Brackets preview window, that same functionality is NOT working when I prevew in a browser. Again, I'm at a complete loss to know why.

I have other odd issues, but will start with those two and just ask if you're aware of any incompatibilities with my configuration, and also would be grateful for any help on the 2 issues I mentioned.

Thank you,

Randy
