### ISSUE TITLE
Extension somehow forget the mediaqueries

### ISSUE THREAD

**Issue by Athax** [brimelow/Response-for-Brackets#71]
For some reason when i edit my media quaries manual, the extension forgets the media quary and does not add a colored line for it: http://i.imgur.com/V39m7LN.png

**Comment by ikbenben** [comment]
@Athax , this is also already known and an issue has been created. See issue #63 and is currently being worked on. For know, you can close the response view and and reopen it for edits made directly in the css file to be reflected in the preview pane

If this addresses, then please close this ticket
