### ISSUE TITLE
Not Working At All

### ISSUE THREAD

**Issue by JameySmallwood** [brimelow/Response-for-Brackets#79]
I cannot get this plugin to function at all.

I watched the [YouTube video](https://www.youtube.com/watch?v=kXTP8XqrSwE) for the plugin and installed it on the latest Brackets version.

I have no other plugins running and cannot get anything from this plugin to function.

I am using the default (Getting Started) pages as well as HTML files from personal projects and I get nothing.

I've installed, uninstalled, installed different versions, restarted brackets, restarted my computer and done whatever else is imaginable.  All I get is the mobile icon to the right and the "Response" button in the nav bar.  None of it does anything.

Any help would be appreciated, would love to see this working.

**Comment by ikbenben** [comment]
@JameySmallwood can you provide steps to recreate? also, what platform are you using? Do you know how to go to open the browser inspector tool? any JS errors you can provide would be helpful. There isn't much that can be done without more information

**Comment by JameySmallwood** [comment]
@ikbenben 

Thanks for your reply.  I made this comment with the last version of brackets, but it seems to be working with the new one.

As for the platform, I'm running the latest version of Windows 8.1.

I'm thrilled to see this working!

**Comment by ikbenben** [comment]
Closing
